// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
// translate-me-ignore-all-file
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB0lnDVO0c3_tUuAlIlUzb6RJdebmnJ1A',
    appId: '1:604693325993:web:ab680b22bdc99f29fb21b8',
    messagingSenderId: '604693325993',
    projectId: 'fruit-hub-ca85f',
    authDomain: 'fruit-hub-ca85f.firebaseapp.com',
    storageBucket: 'fruit-hub-ca85f.firebasestorage.app',
    measurementId: 'G-M8MRGZ46TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2UtwlqLwQ56txOI68glAt9BwCIddNzKY',
    appId: '1:604693325993:android:c3e728abd4a06953fb21b8',
    messagingSenderId: '604693325993',
    projectId: 'fruit-hub-ca85f',
    storageBucket: 'fruit-hub-ca85f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaES7f6WRfFTkWD3lRnvBT9mQ14QtP580',
    appId: '1:604693325993:ios:0a689b022a4ed39efb21b8',
    messagingSenderId: '604693325993',
    projectId: 'fruit-hub-ca85f',
    storageBucket: 'fruit-hub-ca85f.firebasestorage.app',
    iosBundleId: 'com.fruithub.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaES7f6WRfFTkWD3lRnvBT9mQ14QtP580',
    appId: '1:604693325993:ios:0a689b022a4ed39efb21b8',
    messagingSenderId: '604693325993',
    projectId: 'fruit-hub-ca85f',
    storageBucket: 'fruit-hub-ca85f.firebasestorage.app',
    iosBundleId: 'com.fruithub.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB0lnDVO0c3_tUuAlIlUzb6RJdebmnJ1A',
    appId: '1:604693325993:web:a95225ad0a84e7cffb21b8',
    messagingSenderId: '604693325993',
    projectId: 'fruit-hub-ca85f',
    authDomain: 'fruit-hub-ca85f.firebaseapp.com',
    storageBucket: 'fruit-hub-ca85f.firebasestorage.app',
    measurementId: 'G-L8JH9Y0G32',
  );
}
